#!/bin/bash
DIR_PATH=$(dirname $(readlink -f "${BASH_SOURCE:-$0}"))
message=${1:-"Finished working"}
notify-send -t 10000 -i $DIR_PATH/img/cab_view.png "Process Finished" "$message"
paplay $DIR_PATH/tunes/smb_coin.wav