#!/bin/bash
#Desc: Fetch auth code tool
VERSION="v0.0.3"

DIR_PATH=$(dirname $(readlink -f "${BASH_SOURCE:-$0}"))

# Decrypts passwords quietly
# see: https://wiki.archlinux.org/index.php/Mutt#Passwords_management
. <(gpg -qd "$DIR_PATH/.creds.gpg")

# Username and password for your Gmail/G Suite account
username=$my_user
# Password assigned from decrypted file
password=$my_pass
# String that preceds code in the email subject
prefix="AuthCode:"

fetch_mails () {
  # No of recent unread mails to be fetch
  COUNT=$@
  # Parse mails from gmail feed in reverse order
  mails=$(curl  -u $username:$password --silent "https://mail.google.com/mail/feed/atom"\
    |tr -d '\n' | sed 's:</entry>:\n:g'\
    |head -n $COUNT\
    |sed -n \
    's/.*<title>\(.*\)<\/title.*<issued>\([^<]*\).*<author><name>\([^<]*\)<\/name><email>\([^<]*\).*/[\2] \3 (\4): \1/p' \
    |tac)
  if [[ -z $mails ]]; then echo "Couldn't retrieve mails ૮◞ ﻌ ◟ა"; exit 1; fi
  # Read line by line and operate
  while IFS= read -r line; do
    # Search for pattern and extract code
    if [[ $line =~ .*:\ $prefix ]]; then
      # Mails fetch with UTC time, extract it and convert to locale
      date=$(date --date=$(echo $line | sed 's/\[\(.*T.*Z\)\].*/\1/g') "+%x %X")
      auth=$(echo $line | sed "s/.*$prefix \(.*\)$/\1/g")
      # echo $auth
    fi
  done <<< "$mails"
}

echo ૮ ᴖﻌᴖა Sυρєя Ç0∂3 R3тяiєνєя ૮–ﻌ– ა
echo ꒷꒦꒷꒦꒷꒦꒷꒦꒷꒦꒷꒦꒷꒦꒷꒦꒷
echo $VERSION
echo
fetch_mails 10
code=$auth
if [[ -n $code ]]; then
  echo "Your last code (on $date) was: $code ୭̥⋆*｡"
else
  echo No recent codes ૮◞ ﻌ ◟ა
fi
echo "(Run what you need to run in order to get a new code.)"
printf " 🐾  Checking mails (CRTL+C to quit)  "
new_code=$auth
while [ $code == $new_code ]; do
  printf '🌕︎'
  for frame in '🌕︎' '🌔︎' '🌓︎' '🌒︎' '🌑︎' '🌘︎' '🌗︎' '🌖︎' '🌕︎'; do
    echo -en "\b$frame"
    sleep 0.1
  done
  fetch_mails 5
  new_code=$auth
  # echo $auth 
  # sleep 0.1
done
echo
echo "૮ ⚆ﻌ⚆ა New code found ($date): $new_code"
echo "Have fun! ૮ ˙Ⱉ˙ ა rawr!"
$DIR_PATH/alertdone "૮ ⚆ﻌ⚆ა New code found ($date): $new_code"
#sleep 2
#espeak $new_code
